"""empty message

Revision ID: 0b7dd2d0f512
Revises: efb67cebde24
Create Date: 2023-05-05 19:09:07.872566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7dd2d0f512'
down_revision = 'efb67cebde24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode', sa.String(length=80), nullable=True))
        batch_op.drop_column('episode_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_code', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('episode')

    # ### end Alembic commands ###
