"""empty message

Revision ID: 223497cc1042
Revises: ac9388dd1b8c
Create Date: 2023-05-13 20:54:47.134205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223497cc1042'
down_revision = 'ac9388dd1b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_name_key', ['name'])

    # ### end Alembic commands ###
